In [2]:
import torch
print(torch.__version__)  # 설치된 PyTorch 버전 출력
print(torch.cuda.is_available())  # CUDA 사용 가능 여부 확인

if torch.cuda.is_available():
    print(f"GPU 사용 가능: {torch.cuda.get_device_name(0)}")
else:
    print("GPU를 사용할 수 없습니다. CPU를 사용합니다.")

x = torch.rand(3, 3)
y = torch.rand(3, 3)
z = x + y
print("x:", x)
print("y:", y)
print("z:", z)

2.8.0+cpu
False
GPU를 사용할 수 없습니다. CPU를 사용합니다.
x: tensor([[0.4195, 0.1144, 0.3347],
        [0.6223, 0.1585, 0.5821],
        [0.6864, 0.6823, 0.9306]])
y: tensor([[0.0414, 0.8769, 0.5768],
        [0.1249, 0.3538, 0.2261],
        [0.7561, 0.7945, 0.4646]])
z: tensor([[0.4609, 0.9913, 0.9115],
        [0.7472, 0.5123, 0.8082],
        [1.4425, 1.4768, 1.3952]])


In [5]:
import torch
# 1. torch.randn()

# 표준 정규 분포(Standard Normal Distribution)에서 랜덤 샘플 생성
# 평균(𝜇) = 0, 표준편차(𝜎) = 1 인 정규 분포(가우시안 분포)에서 샘플링
# 입력으로 텐서의 크기(shape)를 지정하면 해당 크기의 랜덤 텐서 생성
# 3×3 정규 분포 텐서 생성 (평균 0, 표준편차 1)
tensor = torch.randn(3, 3)
print(tensor)

tensor([[ 0.9998,  1.0961, -0.6748],
        [-0.2393,  1.0817, -0.0638],
        [-0.3947,  0.2885, -0.6095]])


In [6]:
import torch
# 2. torch.rand()

# 균등 분포(Uniform Distribution)에서 랜덤 샘플 생성
# 범위: [0, 1] 사이의 균등한 분포에서 샘플링

tensor = torch.rand(3, 3)  # 0~1 사이 랜덤 값

print(tensor)

tensor([[0.7609, 0.7868, 0.6688],
        [0.2873, 0.7709, 0.3343],
        [0.1955, 0.1235, 0.9751]])


In [8]:
# 3. torch.randint()
#
# 지정한 정수 범위에서 랜덤 정수 샘플 생성
# low (최소값)과 high (최대값)을 지정하여 정수 값을 무작위 생성

tensor = torch.randint(0, 10, (3, 3))  # 0~9 사이 정수 생성

print(tensor)

tensor([[0, 7, 1],
        [2, 9, 9],
        [2, 5, 0]])


In [9]:
# 4. torch.randint_like()
# ✅ 기존 텐서와 같은 shape의 랜덤 정수 텐서 생성

x = torch.ones(3, 3)  # 기존 텐서

rand_tensor = torch.randint_like(x, 0, 10)  # 기존 크기 유지, 0~9 정수 샘플링

print(rand_tensor)

tensor([[0., 5., 6.],
        [3., 3., 9.],
        [3., 3., 6.]])


In [10]:
# 5. torch.normal()
# ✅ 사용자가 지정한 평균(𝜇)과 표준편차(𝜎)로 정규 분포 샘플 생성

mean = torch.tensor([0.0, 2.0, 4.0])  # 평균
std = torch.tensor([1.0, 0.5, 0.1])  # 표준편차

tensor = torch.normal(mean, std)  # 각 요소별로 지정한 평균과 표준편차 적용

print(tensor)

tensor([-0.1203,  1.3325,  4.1356])


In [11]:
# 6. torch.randperm()
# 지정된 범위 내에서 정수를 무작위로 섞음 (순열 생성)

tensor = torch.randperm(10)  # 0~9 정수를 무작위 섞기
print(tensor)

tensor([9, 4, 2, 0, 5, 8, 1, 7, 6, 3])


In [15]:
# 7. torch.bernoulli()
# 베르누이 분포(Bernoulli Distribution)에서 샘플링 (0 또는 1)
# 입력 텐서의 각 요소를 확률로 사용하여 0 또는 1을 반환

probs = torch.tensor([0.2, 0.8, 0.5, 0.9])  # 0~1 사이 확률값

tensor = torch.bernoulli(probs)  # 각 확률에 따라 0 또는 1 생성

print(tensor)

tensor([0., 1., 0., 1.])


In [21]:
# 8. torch.multinomial()
# 다항 분포(Multinomial Distribution)에서 샘플링
# probs 텐서가 주어졌을 때, num_samples 개수만큼 랜덤 샘플을 추출

probs = torch.tensor([0.1, 0.2, 0.3, 0.4])  # 각 요소의 선택 확률
tensor = torch.multinomial(probs, 2, replacement=True)  # 2개 선택 (복원 추출)
print(tensor)

tensor([0, 2])


In [22]:
# 9. torch.seed()
# ✅ 랜덤 시드 고정
# 실험을 재현 가능하도록 하기 위해 사용

torch.manual_seed(42)  # 시드 고정
print(torch.rand(3, 3))  # 동일한 난수 생성

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


In [23]:
# 2-1-인플레이스(In-Place) 연산이란
# 인플레이스(In-Place) 연산은 기존의 **텐서를 변경(덮어쓰기)**하는 연산을 의미합니다.
# 즉, 새로운 텐서를 생성하지 않고, 기존 텐서의 메모리를 직접 수정하는 연산 방식입니다.

import torch

# 기존 텐서
x = torch.tensor([1, 2, 3], dtype=torch.float32)

# 일반 연산 (새로운 텐서 반환)
y = x + 10
print("x (원본):", x)  # 원본 텐서 변경 없음
print("y (새로운 텐서):", y)  # 새로운 텐서 생성됨

# 인플레이스 연산
x.add_(10)
print("x (인플레이스 연산 후):", x)  # 기존 텐서가 변경됨

# 2. 주요 인플레이스 연산
# 연산	일반 연산	인플레이스 연산
# 덧셈	x = x + 5	x.add_(5)
# 뺄셈	x = x - 3	x.sub_(3)
# 곱셈	x = x * 2	x.mul_(2)
# 나눗셈	x = x / 4	x.div_(4)
# 지수 함수	x = x.exp()	x.exp_()
# 정규화	x = x.sqrt()	x.sqrt_()

x (원본): tensor([1., 2., 3.])
y (새로운 텐서): tensor([11., 12., 13.])
x (인플레이스 연산 후): tensor([11., 12., 13.])


In [28]:
# 3. 인플레이스 연산의 장점
# 메모리 사용량 감소

x = torch.randn(1000, 1000)

# 일반 연산 (새로운 메모리 할당)
y = x + 10  # 새로운 텐서가 생성됨

# 인플레이스 연산 (메모리 절약)
x.add_(10)  # 기존 텐서 x가 직접 변경됨

# ➡ 인플레이스 연산을 사용하면 새로운 텐서를 생성하지 않으므로 메모리 사용량이 줄어듦

# 4. 인플레이스 연산의 단점
# 자동 미분(Autograd) 사용 시 문제 발생 가능

x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

y = x.add_(1)  # 인플레이스 연산
y.backward(torch.tensor([1.0, 1.0, 1.0]))  # 오류 발생 가능

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [24]:
# 2-2-PyTorch view() 함수
# torch.view() 함수는 PyTorch에서
# **텐서의 크기를 변경(Reshape)**할 때 사용하는 함수입니다.
# 하지만 view()는 기존 메모리를 유지하면서 크기만 변경하는 특징

# 1. view()의 기본 문법

# tensor.view(shape)
# shape: 변경할 텐서의 크기 ((rows, columns, ...))

# 2. view() 예제: 1D → 2D 변환

import torch

x = torch.arange(6)  # 1D 텐서 (0~5)
print("Original Shape:", x.shape)

xreshaped = x.view(2, 3)  # 2행 3열로 변경

print("Reshaped Shape:", xreshaped.shape)
print(xreshaped)

Original Shape: torch.Size([6])
Reshaped Shape: torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [25]:
# 3. view(-1): 자동 크기 계산
# -1을 사용하면 PyTorch가 자동으로 크기를 계산하여 설정합니다.

x = torch.arange(12)
xreshaped = x.view(3, -1)  # 열(-1)은 자동 계산됨

print(xreshaped.shape)
print(xreshaped)

torch.Size([3, 4])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [29]:
# 4. 3D → 2D 변환 예제
x = torch.arange(24).view(2, 3, 4)  # 3D 텐서 생성 (배치=2, 행=3, 열=4)

print("3D Tensor Shape:", x.shape)

xflattened = x.view(2, -1)  # 배치 유지, 나머지는 자동 조정
print("Flattened Shape:", xflattened.shape)

# 5. view() 사용 시 주의할 점
# 연속된 메모리(Contiguous) 필요

# view()는 메모리 연속성이 유지되는 경우에만 사용 가능
# 만약 연속적이지 않다면 .contiguous().view()를 사용해야 함


x = torch.randn(2, 3, 4)  # (Batch=2, Rows=3, Cols=4)
xt = x.transpose(0, 1)    # (Rows=3, Batch=2, Cols=4) → 메모리 비연속

3D Tensor Shape: torch.Size([2, 3, 4])
Flattened Shape: torch.Size([2, 12])


In [ ]:
# 6. view()와 reshape() 차이
# 함수	특징
# view()	메모리 연속성 유지 필요, 속도 빠름
# reshape()	메모리 연속성 없어도 사용 가능

x = torch.randn(2, 3)
xt = x.transpose(0, 1)  # 차원 변경 → 메모리 비연속

# view() 오류 발생
try:
    xview = xt.view(6)
except RuntimeError as e:
    print("view() Error:", e)

# reshape()는 자동으로 해결
xreshape = xt.reshape(6)
print("reshape() 성공:", xreshape.shape)

# ✅ 메모리 연속성이 없는 경우 view()는 실패하지만 reshape()는 가능!

In [36]:
# 2-3-squeeze() vs unsqueeze() 함수 차이점
# PyTorch에서 squeeze()와 unsqueeze()는 텐서의 차원을 변경하는 함수입니다.

# squeeze(): 크기가 1인 차원 제거

# squeeze()는 크기가 1인 차원을 자동으로 제거합니다.
import torch

x = torch.randn(1, 3, 1, 4)  # (Batch=1, Channels=3, Height=1, Width=4)

x_squeezed = x.squeeze()  # 크기가 1인 차원을 제거

print(x.shape)          # torch.Size([1, 3, 1, 4])
print(x_squeezed.shape) # torch.Size([3, 4])

x_squeezed_1 = x.squeeze(0)  # 0번 차원(크기가 1인 경우만) 제거
x_squeezed_2 = x.squeeze(2)  # 2번 차원(크기가 1인 경우만) 제거

print(x_squeezed_1.shape)  # torch.Size([3, 1, 4])
print(x_squeezed_2.shape)  # torch.Size([1, 3, 4])

torch.Size([1, 3, 1, 4])
torch.Size([3, 4])
torch.Size([3, 1, 4])
torch.Size([1, 3, 4])


In [40]:
y = torch.randn(3, 4)  # (3, 4) 형태
y_unsqueezed = y.unsqueeze(0)  # 0번 차원 추가

print(y.shape)           # torch.Size([3, 4])
print(y_unsqueezed.shape) # torch.Size([1, 3, 4])

torch.Size([3, 4])
torch.Size([1, 3, 4])


In [38]:
# 2D 텐서 생성 (2x3 크기)
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Shape: (2,3)
y = torch.tensor([[7, 8, 9], [10, 11, 12]])  # Shape: (2,3)

# unsqueeze(0)을 통해 새로운 차원 추가 후 cat() 적용
z = torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0)

# 결과 출력
print("Original x shape:", x.shape)
print("Original y shape:", y.shape)
print("After unsqueeze and cat, z shape:", z.shape)
print("z Tensor:\n", z)

Original x shape: torch.Size([2, 3])
Original y shape: torch.Size([2, 3])
After unsqueeze and cat, z shape: torch.Size([2, 2, 3])
z Tensor:
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [39]:
# 2. 텐서 크기(Shape) 이해
# PyTorch에서 tensor.shape을 확인하면 텐서의 차원과 크기를 알 수 있습니다.

import torch

# 0D 텐서 (스칼라)
scalar = torch.tensor(42)
print("Scalar Shape:", scalar.shape)  # ()

# 1D 텐서 (벡터)
vector = torch.tensor([1, 2, 3])
print("Vector Shape:", vector.shape)  # (3,)

# 2D 텐서 (행렬)
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Matrix Shape:", matrix.shape)  # (2, 3)

# 3D 텐서 (다차원 배열)
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Tensor Shape:", tensor_3d.shape)  # (2, 2, 2)

Scalar Shape: torch.Size([])
Vector Shape: torch.Size([3])
Matrix Shape: torch.Size([2, 3])
3D Tensor Shape: torch.Size([2, 2, 2])


In [48]:
# 3. 텐서 요소 변화 예시

# 1) reshape()을 활용한 형태 변경

x = torch.arange(6)  # [0, 1, 2, 3, 4, 5]
print("Original Shape:", x.shape)  # (6,)
print("------------")
x_reshaped = x.reshape(2, 3)  # 2행 3열로 변경
print("Reshaped Shape:", x_reshaped.shape)  # (2, 3)
print(x_reshaped)

# reshape을 사용하면 텐서의 shape을 변경 가능
# 데이터의 개수(요소 개수)는 그대로 유지되지만, 차원만 변경됨

Original Shape: torch.Size([6])
------------
Reshaped Shape: torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [49]:
# 2) unsqueeze()를 활용한 차원 추가


x = torch.tensor([1, 2, 3])
print("Original Shape:", x.shape)  # (3,)
print("------------")
x_unsqueezed = x.unsqueeze(0)  # 차원 추가 (배치 차원 추가)
print("Unsqueezed Shape:", x_unsqueezed.shape)  # (1, 3)

# unsqueeze(dim=0)을 사용하면 (3,) → (1, 3)로 차원이 추가됨
# CNN 모델에서 배치 차원을 추가할 때 자주 사용됨

Original Shape: torch.Size([3])
------------
Unsqueezed Shape: torch.Size([1, 3])


In [52]:
# 3) squeeze()를 활용한 차원 축소


x = torch.tensor([[1, 2, 3]])  # (1, 3)
print("Original Shape:", x.shape)
print("------------")
x_squeezed = x.squeeze()
print("Squeezed Shape:", x_squeezed.shape)  # (3,)
print("------------")
# 4) permute()를 활용한 차원 순서 변경

x = torch.randn(3, 4, 5)  # (채널, 높이, 너비)
print("Original Shape:", x.shape)  # (3, 4, 5)
print("------------")
x_permuted = x.permute(1, 2, 0)  # (높이, 너비, 채널)로 변경

print("Permuted Shape:", x_permuted.shape)  # (4, 5, 3)

Original Shape: torch.Size([1, 3])
------------
Squeezed Shape: torch.Size([3])
------------
Original Shape: torch.Size([3, 4, 5])
------------
Permuted Shape: torch.Size([4, 5, 3])


In [53]:
# 4. 텐서 연산을 통한 요소 변화

x = torch.tensor([[1, 2], [3, 4]])
print("Original Tensor:")
print(x)
print("------------")
# 텐서 값 변경 (연산 수행)
y = x * 2  # 요소별 연산 (모든 원소를 2배)
print("After Multiplication by 2:")
print(y)
print("------------")
# 요소별 제곱 연산
z = x ** 2
print("After Squaring:")
print(z)

# 0D 텐서 (스칼라):  숫자 하나
# 1D 텐서 (벡터):   리스트 형태의 배열
# 2D 텐서 (행렬):   행과 열이 있는 배열
# 3D 이상 텐서:     다차원 배열

# reshape()	    크기 변경 (요소 개수 유지)	(6,) → (2, 3)
# unsqueeze()	차원 추가	(3,) → (1, 3)
# squeeze()	    차원 제거	(1, 3, 1) → (3,)
# permute()	    차원 순서 변경	(3, 4, 5) → (4, 5, 3)

Original Tensor:
tensor([[1, 2],
        [3, 4]])
------------
After Multiplication by 2:
tensor([[2, 4],
        [6, 8]])
------------
After Squaring:
tensor([[ 1,  4],
        [ 9, 16]])


In [54]:
# 1. 입력 데이터 X와 정답 데이터 Y의 shape

X = torch.tensor([[0, 0],
                  [0, 1],
                  [1, 0],
                  [1, 1]], dtype=torch.float32)  # 입력값
Y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32)  # 정답값

# 데이터	내용	Shape
# X	4개의 샘플, 각 샘플은 2개의 입력 특성(0 또는 1)	(4, 2)
# Y	4개의 샘플, 각 샘플의 정답(0 또는 1)	(4, 1)

# 즉, X는 (batch_size, input_dim) = (4, 2) 형태의 입력을 가짐
# 정답 Y는 (batch_size, output_dim) = (4, 1) 형태의 출력을 기대함


# 2. forward() 함수에서 데이터 흐름과 shape 변화

# def forward(self, x):
#     x = self.activation(self.hidden(x))  # 은닉층 활성화
#     x = self.activation(self.output(x))  # 출력층 활성화
#     return x

# (1) 입력층 → 은닉층 변환 (self.hidden(x))

# self.hidden = nn.Linear(2, 2)  # (input_dim=2 → hidden_dim=2)
# X.shape = (4, 2) → hidden(x)을 통과하면 (4, 2)
# 선형 변환 공식: Z1 = X * W1 + b1

# (2) 은닉층 활성화 (self.activation(hidden(x)))

# 활성화 함수 Sigmoid 적용 → shape 변화 없음
# x.shape = (4, 2)

# (3) 은닉층 → 출력층 변환 (self.output(x))

# self.output = nn.Linear(2, 1)  # (hidden_dim=2 → output_dim=1)
# x.shape = (4, 2) → output(x)을 통과하면 (4, 1)

# 선형 변환 공식: Z2 = A1 * W2 + b2
# => (4,2) × (2,1) = (4,1)

# (4) 출력층 활성화 (self.activation(output(x)))
# 활성화 함수 Sigmoid 적용 → shape 변화 없음
# 최종 출력 x.shape = (4, 1)

# 3. 데이터 흐름 Shape 변화 요약

# 레이어	연산	Shape 변화

# 입력 데이터	X	                                :(4, 2)
# 은닉층 선형 변환	self.hidden(x)	                :(4, 2)
# 은닉층 활성화 함수	self.activation(hidden(x))	:(4, 2)
# 출력층 선형 변환	self.output(x)	                :(4, 1)
# 출력층 활성화 함수	self.activation(output(x))	:(4, 1)
# 최종 출력	Y_hat	                            :(4, 1)

# 4. 실제 shape 확인 코드

import torch
import torch.nn as nn

class XOR_NN(nn.Module):
    def __init__(self):
        super(XOR_NN, self).__init__()
        self.hidden = nn.Linear(2, 2)  # 입력 2 → 은닉층 2
        self.output = nn.Linear(2, 1)  # 은닉층 2 → 출력층 1
        self.activation = nn.Sigmoid()  # 활성화 함수

    def forward(self, x):
        print("입력 데이터 shape:", x.shape)  # (4, 2)
        x = self.hidden(x)
        print("은닉층 통과 후 shape:", x.shape)  # (4, 2)
        x = self.activation(x)
        print("은닉층 활성화 후 shape:", x.shape)  # (4, 2)
        x = self.output(x)
        print("출력층 통과 후 shape:", x.shape)  # (4, 1)
        x = self.activation(x)
        print("출력층 활성화 후 shape:", x.shape)  # (4, 1)
        return x

# 모델 생성
model = XOR_NN()

# 입력 데이터
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)

# 모델 실행
output = model(X)

입력 데이터 shape: torch.Size([4, 2])
은닉층 통과 후 shape: torch.Size([4, 2])
은닉층 활성화 후 shape: torch.Size([4, 2])
출력층 통과 후 shape: torch.Size([4, 1])
출력층 활성화 후 shape: torch.Size([4, 1])


In [55]:
# 3차원 텐서의 기본 개념
# 3차원 텐서는 다음과 같은 **3개의 차원(Dimension)**을 가집니다.

# 3D Tensor Shape: (D1, D2, D3)
# 첫 번째 차원 (D_1) → 일반적으로 배치 크기(Batch Size), 채널 수(Channel)
# 두 번째 차원 (D_2) → 행(Row) 또는 높이(Height)
# 세 번째 차원 (D_3) → 열(Column) 또는 너비(Width)

# 1. 3D 텐서 생성 및 각 인덱스 별 위치 확인

import torch

# 3D 텐서 생성 (배치=2, 높이=3, 너비=4)
tensor_3d = torch.tensor([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],  # 첫 번째 배치

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]  # 두 번째 배치
])

print("3D Tensor Shape:", tensor_3d.shape)  # (2, 3, 4)

3D Tensor Shape: torch.Size([2, 3, 4])


In [56]:
# 2. 각 차원별 인덱스 위치

# 텐서에서 특정 인덱스의 값을 참조할 때 (배치, 높이, 너비) 순서로 접근합니다.
# tensor_3d = torch.tensor([
#     [[1, 2, 3, 4],
#      [5, 6, 7, 8],
#      [9, 10, 11, 12]],  # 첫 번째 배치
#-----------------------------------
#     [[13, 14, 15, 16],
#      [17, 18, 19, 20],
#      [21, 22, 23, 24]]  # 두 번째 배치
# ])
print("tensor_3d[0, 0, 0]:", tensor_3d[0, 0, 0])  #첫 번째 배치, 첫 번째 행, 첫 번째 열	1
print("tensor_3d[0, 0, 1]:", tensor_3d[0, 0, 1])  #첫 번째 배치, 첫 번째 행, 두 번째 열	2
print("tensor_3d[0, 1, 2]:", tensor_3d[0, 1, 2])  #첫 번째 배치, 두 번째 행, 세 번째 열	7
print("tensor_3d[1, 2, 3]:", tensor_3d[1, 2, 3])  #두 번째 배치, 세 번째 행, 네 번째 열	24

tensor_3d[0, 0, 0]: tensor(1)
tensor_3d[0, 0, 1]: tensor(2)
tensor_3d[0, 1, 2]: tensor(7)
tensor_3d[1, 2, 3]: tensor(24)


In [63]:
# (1) 특정 배치 선택 (tensor_3d[0])

print(tensor_3d[0])  # 첫 번째 배치 데이터 출력
# tensor([[ 1,  2,  3,  4],
#         [ 5,  6,  7,  8],
#         [ 9, 10, 11, 12]])

print("--------------------------")
# (2) 특정 행 선택 (tensor_3d[1, 1])

print(tensor_3d[1, 1])
print("--------------------------")
# (3) 특정 열 선택 (tensor_3d[:, :, 2])

print(tensor_3d[:, :, 2]) # 모든 배치에서 3번째 열 선택

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
--------------------------
tensor([17, 18, 19, 20])
--------------------------
tensor([[ 3,  7, 11],
        [15, 19, 23]])


In [64]:
# 4. permute()를 활용한 위치 변경
 # permute(1, 2, 0): (배치, 높이, 너비) → (높이, 너비, 배치)


tensor_permuted = tensor_3d.permute(1, 2, 0)  # (높이, 너비, 배치)
print("Permuted Shape:", tensor_permuted.shape)
# ➡ 배치가 마지막으로 이동하고, 높이가 첫 번째 차원으로 변경됨

# 다른예시: permute(2, 0, 1): (배치, 높이, 너비) → (너비, 배치, 높이)

# 5. 결론
 # 3D 텐서는 (배치, 높이, 너비) = (D_1, D_2, D_3) 형태
 # 인덱싱(tensor_3d[i, j, k])을 사용하여 특정 위치 선택 가능
 # permute()를 사용하면 차원의 순서를 변경 가능
 # 특정 차원 선택 시 :를 활용하여 전체 배치 또는 특정 행/열만 가져올 수 있음

Permuted Shape: torch.Size([3, 4, 2])


In [ ]:
# 2-5-split() vs chunk() 차이점

 # split() vs chunk() 차이점
# torch.split()과 torch.chunk()는
 # PyTorch에서 텐서를 특정 크기 또는 개수로 나누는 함수

In [65]:
# split() 함수
# split(batch_size, dim) : 주어진 크기(batch_size)로 텐서를 나눔.
# 마지막 부분의 크기는 남은 요소 개수에 따라 조정될 수 있음.

import torch

x = torch.FloatTensor(10, 4)  # (10, 4) 크기의 텐서 생성

splits = x.split(4, dim=0)  # 첫 번째 차원(행 기준)으로 크기 4씩 나눔

for s in splits:
    print(s.size())
    # 마지막 조각은 크기가 다를 수 있음. (총 10개 데이터를 4개씩 나누면 4+4+2)

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [66]:
# chunk() 함수
 # chunk(n_chunks, dim): 지정한 개수(n_chunks)로 텐서를 균등하게 나눔.
 #    split()과 다르게 크기가 자동으로 균등하게 배분됨.

x = torch.FloatTensor(8, 4)  # (8, 4) 크기의 텐서 생성
chunks = x.chunk(3, dim=0)  # 3개로 나눔

for c in chunks:
    print(c.size())
    # split()과 유사하지만, 균등하게 분할할 수 있도록 자동으로 크기를 맞춤.

# -> 정확한 크기(batch_size)로 나누려면 split() 사용.
    # 균등하게 n개로 나누려면 chunk() 사용.

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


In [72]:
# index_select()
    # 특정 차원의 특정 인덱스만 선택하여 새로운 텐서를 생성하는 함수
# torch.index_select(input, dim, index)
#                     input : 원본 텐서
#                         dim : 선택할 차원 (0=행, 1=열, ...)
#                             index : 선택할 인덱스 리스트

import torch

x = torch.arange(12).reshape(4, 3)  # (4,3) 텐서 생성
print("Original Tensor:\n", x)
print("---------------------------")

index = torch.tensor([1, 3], dtype=torch.long) # 2번째, 4번째 행 선택

# 행 선택 (dim=0 -> 행 방향)
selected_rows = torch.index_select(x, dim=0, index=index)

print("Selected Rows:\n", selected_rows)
print("---------------------------")
# 열 선택 (dim=1 → 열 방향으로 선택)
index = torch.tensor([0, 2], dtype=torch.long)  # 1 번째, 3 번째 열 선택
selected_cols = torch.index_select(x, dim=1, index=index)

print("Selected Columns:\n", selected_cols)

Original Tensor:
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
---------------------------
Selected Rows:
 tensor([[ 3,  4,  5],
        [ 9, 10, 11]])
---------------------------
Selected Columns:
 tensor([[ 0,  2],
        [ 3,  5],
        [ 6,  8],
        [ 9, 11]])


In [ ]:
# index_select() vs tensor[indices] 차이

# 직접 인덱싱
selected_rows = x[[1, 3]]
print(selected_rows)

# index_select()는 메모리 연속성이 유지됨.
# x[[...]]는 메모리 비연속적인 텐서를 생성할 수 있음.

# index_select(x, dim=0, index) / dim=0 행

# index_select(x, dim=1, index) / dim=1 열

# x[[indices]]	특정 행 선택 (직접 인덱싱)	x[[1,3]]

In [76]:
# torch.cat() 함수
    # 여러 개의 텐서를 특정 차원(dim)으로 연결(Concatenate)하는 함수
# torch.cat(tensors, dim)
            # tensors : 연결할 텐서들의 리스트 [tensor1, tensor2, ...]
                    # dim : 연결할 차원 (0=행 방향, 1=열 방향, ...)

# 행 방향(dim=0)으로 연결
import torch

a = torch.tensor([[1, 2], [3, 4]])  # (2,2)
b = torch.tensor([[5, 6], [7, 8]])  # (2,2)

# 행 방향(dim=0)으로 연결
c = torch.cat([a, b], dim=0)

print("Concatenated Tensor (dim=0):\n", c)
print("---------------------------")
print("Shape:", c.shape)
# (2,2) + (2,2) → (4,2)... 행이 늘어남(수직 방향으로 연결).
print("---------------------------")
# 열 방향(dim=1)으로 연결
c = torch.cat([a, b], dim=1)  # 열 방향으로 연결

print("Concatenated Tensor (dim=1):\n", c)
print("---------------------------")
print("Shape:", c.shape)

# cat()을 사용할 때 주의할 점
    # 차원이 동일해야 함. dim 방향만 다를 수 있음.

    # 오류 예제

    # a = torch.tensor([[1, 2]])  # (1,2)
    # b = torch.tensor([[3], [4]])  # (2,1)
    # -> c = torch.cat([a, b], dim=0)  # 서로 다른 shape → 오류 발생!

Concatenated Tensor (dim=0):
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
---------------------------
Shape: torch.Size([4, 2])
---------------------------
Concatenated Tensor (dim=1):
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
Shape: torch.Size([2, 4])


In [ ]:
# 2-8-torch.stack() : 새로운 차원을 추가하면서 여러 텐서를 쌓는(stack) 함수
# torch.stack(tensors, dim)
            # tensors : 스택할 텐서들의 리스트 [tensor1, tensor2, ...]
                    # dim : 새로운 차원을 추가할 위치

# cat()은 기존 차원에서 연결 (새로운 차원 추가 ❌).
# stack()은 새로운 차원 추가하면서 연결 (새로운 차원 추가 ⭕).

In [81]:
import torch

a = torch.tensor([1, 2, 3])  # (3,)
b = torch.tensor([4, 5, 6])  # (3,)

c = torch.stack([a, b], dim=0)  # 새로운 차원 추가

print("Stacked Tensor (dim=0):\n", c)

print("Shape:", c.shape)
# 결과 shape: (2,3) → 기존 (3,) 텐서 2개를 쌓아서 (2,3) 텐서 생성.
print("---------------------------")
c = torch.stack([a, b], dim=1)  # 새로운 차원을 1번 위치에 추가

print("Stacked Tensor (dim=1):\n", c)

print("Shape:", c.shape)

Stacked Tensor (dim=0):
 tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
---------------------------
Stacked Tensor (dim=1):
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
Shape: torch.Size([3, 2])


In [82]:
# 2D 텐서에 적용
a = torch.tensor([[1, 2], [3, 4]])  # (2,2)
b = torch.tensor([[5, 6], [7, 8]])  # (2,2)

c = torch.stack([a, b], dim=0)
print("Stacked Tensor (dim=0):\n", c)
print("Shape:", c.shape)
# dim=0으로 stack하면 (2,2) → (2,2,2) (새로운 차원 추가됨)

Stacked Tensor (dim=0):
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


In [83]:
# 2-9-expand() 예제

import torch

# 3D 텐서 생성 (2, 1, 2)
x = torch.FloatTensor([[[1, 2]], [[3, 4]]])
print("Original x shape:", x.shape)
print("---------------------------")
# expand()를 사용하여 새로운 차원 확장 (2, 3, 2)
y = x.expand(2, 3, 2)

# 결과 출력
print("Expanded y shape:", y.shape)
print("---------------------------")
print("Expanded y Tensor:\n", y)

Original x shape: torch.Size([2, 1, 2])
Expanded y shape: torch.Size([2, 3, 2])
Expanded y Tensor:
 tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


In [85]:
# 2-10-torch.randperm() :0부터 n-1까지의 숫자를 랜덤한 순서로 정렬한 텐서를 반환

import torch

# 0부터 9까지의 숫자를 무작위로 섞기 (순열 생성)
perm = torch.randperm(10)

print("Random Permutation:", perm)
print("---------------------------")

# 데이터셋의 인덱스 랜덤 섞기
data = torch.tensor([10, 20, 30, 40, 50])
indices = torch.randperm(len(data))

shuffled_data = data[indices]

print("Original Data:", data)
print("Shuffled Data:", shuffled_data)

Random Permutation: tensor([7, 3, 4, 9, 6, 1, 0, 5, 2, 8])
---------------------------
Original Data: tensor([10, 20, 30, 40, 50])
Shuffled Data: tensor([20, 30, 10, 40, 50])


In [88]:
# 2-11-torch.argmax(dim=n)

import torch

# 3x3 텐서 생성
x = torch.tensor([[1, 7, 3],
                  [4, 2, 9],
                  [8, 6, 5]])

# argmax(dim=0): 열 방향(세로)에서 최대값의 인덱스 찾기
argmax_dim0 = torch.argmax(x, dim=0)

# argmax(dim=1): 행 방향(가로)에서 최대값의 인덱스 찾기
argmax_dim1 = torch.argmax(x, dim=1)

# 결과 출력
print("Tensor:\n", x)
print("\nArgmax along dim=0 (column-wise):", argmax_dim0)
print("---------------------------------------")
print("Argmax along dim=1 (row-wise):", argmax_dim1)



# torch.argmax(x, dim=0) → 열 방향 (dim=0)에서 최대값의 인덱스 반환

# 첫 번째 열 [1, 4, 8] → 최대값: 8 (인덱스 2)
# 두 번째 열 [7, 2, 6] → 최대값: 7 (인덱스 0)
# 세 번째 열 [3, 9, 5] → 최대값: 9 (인덱스 1)
# 결과: tensor([2, 0, 1])

# torch.argmax(x, dim=1) → 행 방향 (dim=1)에서 최대값의 인덱스 반환

# 첫 번째 행 [1, 7, 3] → 최대값: 7 (인덱스 1)
# 두 번째 행 [4, 2, 9] → 최대값: 9 (인덱스 2)
# 세 번째 행 [8, 6, 5] → 최대값: 8 (인덱스 0)
# 결과: tensor([1, 2, 0])

Tensor:
 tensor([[1, 7, 3],
        [4, 2, 9],
        [8, 6, 5]])

Argmax along dim=0 (column-wise): tensor([2, 0, 1])
---------------------------------------
Argmax along dim=1 (row-wise): tensor([1, 2, 0])


In [90]:
# 2-12-torch.topk()

import torch

# 3x3 텐서 생성
x = torch.tensor([[1, 7, 3],
                  [4, 2, 9],
                  [8, 6, 5]])

# 각 행(row)에서 최대값 1개(`k=1`) 찾기 (dim=-1 → 마지막 차원 기준)
    # dim=-1은 마지막 차원(여기서는 행 방향)을 기준으로 동작.
topk_values, topk_indices = torch.topk(x, k=1, dim=-1)

# 결과 출력
print("Tensor:\n", x)
print("\nTop-1 values along dim=-1 (row-wise):\n", topk_values)
print("Top-1 indices along dim=-1:", topk_indices)

# topk_values: 각 행에서 최대값 반환.
# topk_indices: 각 행에서 최대값의 인덱스 반환.

# torch.topk()를 사용하면 k개의 최댓값과 해당 인덱스를 쉽게 찾을 수 있음.

Tensor:
 tensor([[1, 7, 3],
        [4, 2, 9],
        [8, 6, 5]])

Top-1 values along dim=-1 (row-wise):
 tensor([[7],
        [9],
        [8]])
Top-1 indices along dim=-1: tensor([[1],
        [2],
        [0]])
